/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mg.service.frontend;

import com.mg.service.backend.model.Memory;
import com.mg.service.backend.model.MemoryBuilder;
import org.testng.collections.Lists;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 * @author damak
 */
public class FilePanel extends JPanel {

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JTable MemoryTable;
	private JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

	/**
	 * Creates new form FilePanel
	 */
	public FilePanel(List<Memory> memories) {
		JLabel label = new JLabel("Liste de Mémoires");
		add(label);
		initComponents(memories);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 *
	 * @param memories
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents(List<Memory> memories) {

		jScrollPane1 = new JScrollPane();
		MemoryTable = new JTable();

		MemoryTable.setAutoCreateRowSorter(true);

		MemoryTable.setModel(new MemoryTableModel(memories));
		MemoryTable.setColumnSelectionAllowed(true);
		jScrollPane1.setViewportView(MemoryTable);
		MemoryTable.getColumnModel().getSelectionModel().setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

		GroupLayout layout = new GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 375, GroupLayout.PREFERRED_SIZE)
								.addContainerGap(19, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addContainerGap(35, Short.MAX_VALUE)
								.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 239, GroupLayout.PREFERRED_SIZE)
								.addGap(26, 26, 26))
		);
		add(MemoryTable, BorderLayout.CENTER);

	}// </editor-fold>//GEN-END:initComponents


	public static void main(String args[]) {
		/* Create and display the form */
		EventQueue.invokeLater(() -> {
			new FilePanel(Lists.newArrayList(new MemoryBuilder().setAccount(444.4D).createMemory())).setVisible(true);
		});
	}
}

